import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  const meta = {
    title: "My Open Graph Project",
    description: " Officia incididunt aliqua mollit nulla officia nisi mollit amet esse aliqua minim eiusmod nisi ut.",
    imageUrl: "https://res.cloudinary.com/ugwutotheeshoes/image/upload/v1647525808/protocolo-open-graph_cqwxrx.jpg",
    type: 'article',
    twitterHandle: "https://twitter.com/ugwutotheeshoes",
    date: '17/03/2022',
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:type" content={meta.type} />
        <meta property="og:site_name" content="Emmanuel Ugwu" />
        <meta property="og:description" content={meta.description} />
        <meta property="og:title" content={meta.title} />
        <meta property="og:image" content={meta.imageUrl} />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content={meta.twitterHandle} />
        <meta name="twitter:title" content={meta.title} />
        <meta name="twitter:description" content={meta.description} />
        <meta name="twitter:image" content={meta.imageUrl} />
        {meta.date && (
          <meta property="article:published_time" content={meta.date} />
        )}
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Open Graph Project
        </h1>

        <p className={styles.description}>
          Officia incididunt aliqua mollit nulla officia nisi mollit amet esse aliqua minim eiusmod nisi ut. Deserunt elit eiusmod consectetur nulla ex tempor consequat et pariatur. Occaecat sunt est laborum consectetur reprehenderit. Pariatur excepteur minim ex irure adipisicing elit officia ullamco ad irure duis labore amet. Lorem eiusmod est laborum laboris ullamco irure nulla labore ad qui. Ullamco officia velit ipsum aute ex duis elit cupidatat cupidatat nostrud cupidatat cupidatat.
        </p>
      </main>
    </div>
  )
}
